// ubg235 Server
const REDIRECT_GUIDE= {
    "1v1lol": "https://AUG44.com/1v1lol.html",
    "3d-bowling": "https://AUG44.com/3d-bowling.html",
    "3d-car-simulator": "https://AUG44.com/3d-car-simulator.html",
    "3d-moto-simulator-2": "https://AUG44.com/3d-moto-simulator-2.html",
    "8ball-pool": "https://AUG44.com/8ball-pool.html",
    "adventure-drivers": "https://AUG44.com/adventure-drivers.html",
    "among-us": "https://AUG44.com/among-us.html",
    "angry-gran-run": "https://AUG44.com/angry-gran-run.html",
    "awesome-tanks-2": "https://AUG44.com/awesome-tanks-2.html",
    "apple-shooter": "https://AUG44.com/apple-shooter.html",
    "axis-football-league": "https://AUG44.com/axis-football-league.html",
    "bad-ice-cream-3": "https://AUG44.com/bad-ice-cream-3.html",
    "ballistic": "https://AUG44.com/ballistic.html",
    "basket-and-ball": "https://AUG44.com/basket-and-ball.html",
    "basket-random": "https://AUG44.com/basket-random.html",
    "basketball-legends-2020": "https://AUG44.com/basketball-legends-2020.html",
    "basketball-stars": "https://AUG44.com/basketball-stars.html",
    "big-tower-tiny-square": "https://AUG44.com/big-tower-tiny-square.html",
    "bike-trials-winter-2": "https://AUG44.com/bike-trials-winter-2.html",
    "blumgi-rocket": "https://AUG44.com/blumgi-rocket.html",
    "bob-the-robber-2": "https://AUG44.com/bob-the-robber-2.html",
    "bob-the-robber-4": "https://AUG44.com/bob-the-robber-4.html",
    "bomb-it-7": "https://AUG44.com/bomb-it-7.html",
    "breaking-the-bank": "https://AUG44.com/breaking-the-bank.html",
    "bullet-force": "https://AUG44.com/bullet-force.html",
    "burnin-rubber-5-xs": "https://AUG44.com/burnin-rubber-5-xs.html",
    "burnout-drift-hilltop": "https://AUG44.com/burnout-drift-hilltop.html",
    "burnin-rubber": "https://AUG44.com/burnin-rubber.html",
    "burrito-bison-launcha-libre": "https://AUG44.com/burrito-bison-launcha-libre.html",
    "bus-parking-3d": "https://AUG44.com/bus-parking-3d.html",
    "candy-jump": "https://AUG44.com/candy-jump.html",
    "car-drift-racers-2": "https://AUG44.com/car-drift-racers-2.html",
    "car-rush": "https://AUG44.com/car-rush.html",
    "car-simulator-arena": "https://AUG44.com/car-simulator-arena.html",
    "cars-thief": "https://AUG44.com/cars-thief.html",
    "cartoon-mini-racing": "https://AUG44.com/cartoon-mini-racing.html",
    "circloo-2": "https://AUG44.com/circloo-2.html",
    "circloo": "https://AUG44.com/circloo.html",
    "city-car-driving-stunt-master": "https://AUG44.com/city-car-driving-stunt-master.html",
    "city-rider": "https://AUG44.com/city-rider.html",
    "clicker-heroes": "https://AUG44.com/clicker-heroes.html",
    "color-road": "https://AUG44.com/color-road.html",
    "color-tunnel-2": "https://AUG44.com/color-tunnel-2.html",
    "color-tunnel": "https://AUG44.com/color-tunnel.html",
    "cookie-clicker": "https://AUG44.com/cookie-clicker.html",
    "crazy-tunnel-3d": "https://AUG44.com/crazy-tunnel-3d.html",
    "crossy-road": "https://AUG44.com/crossy-road.html",
    "cubefield": "https://AUG44.com/cubefield.html",
    "demolition-derby-crash-racing": "https://AUG44.com/demolition-derby-crash-racing.html",
    "doodle-jump": "https://AUG44.com/doodle-jump.html",
    "doom-2": "https://AUG44.com/doom-2.html",
    "drift-boss": "https://AUG44.com/drift-boss.html",
    "drift-hunters": "https://AUG44.com/drift-hunters.html",
    "drive-mad": "https://AUG44.com/drive-mad.html",
    "drive-mad": "https://AUG44.com/drive-mad.html",
    "e-scooter": "https://AUG44.com/e-scooter.html",
    "eagle-ride": "https://AUG44.com/eagle-ride.html",
    "electron-dash": "https://AUG44.com/electron-dash.html",
    "eggy-car": "https://AUG44.com/eggy-car.html",
    "endless-truck": "https://AUG44.com/endless-truck.html",
    "endless-tunnel": "https://AUG44.com/endless-tunnel.html",
    "escaping-the-prison": "https://AUG44.com/escaping-the-prison.html",
    "extreme-car-parking": "https://AUG44.com/extreme-car-parking.html",
    "extreme-pamplona": "https://AUG44.com/extreme-pamplona.html",
    "fire-truck-rescue": "https://AUG44.com/fire-truck-rescue.html",
    "fire-truck": "https://AUG44.com/fire-truck.html",
    "fireboy-and-watergirl-2": "https://AUG44.com/fireboy-and-watergirl-2.html",
    "fireboy-and-watergirl-3": "https://AUG44.com/fireboy-and-watergirl-3.html",
    "fireboy-and-watergirl-4": "https://AUG44.com/fireboy-and-watergirl-4.html",
    "fireboy-and-watergirl-5": "https://AUG44.com/fireboy-and-watergirl-5.html",
    "fireboy-and-watergirl-6": "https://AUG44.com/fireboy-and-watergirl-6.html",
    "fireboy-and-watergirl": "https://AUG44.com/fireboy-and-watergirl.html",
    "fleeing-the-complex": "https://AUG44.com/fleeing-the-complex.html",
    "flying-car-simulator": "https://AUG44.com/flying-car-simulator.html",
    "football-legends": "https://AUG44.com/football-legends.html",
    "fortnite": "https://AUG44.com/fortnite.html",
    "fortride-open-world": "https://AUG44.com/fortride-open-world.html",
    "galaga": "https://AUG44.com/galaga.html",
    "getaway-shootout": "https://AUG44.com/getaway-shootout.html",
    "go-kart-go-ultra": "https://AUG44.com/go-kart-go-ultra.html",
    "gun-mayhem-2": "https://AUG44.com/gun-mayhem-2.html",
    "gun-blood": "https://AUG44.com/gun-blood.html",
    "gun-mayhem-3": "https://AUG44.com/gun-mayhem-3.html",
    "gun-mayhem": "https://AUG44.com/gun-mayhem.html",
    "highway-racer-3d": "https://AUG44.com/highway-racer-3d.html",
    "highway-rider-extreme": "https://AUG44.com/highway-rider-extreme.html",
    "icycle": "https://AUG44.com/icycle.html",
    "idle-breakout": "https://AUG44.com/idle-breakout.html",
    "idle-miner": "https://AUG44.com/idle-miner.html",
    "idle-mining-empire": "https://AUG44.com/idle-mining-empire.html",
    "idle-startup-tycoon": "https://AUG44.com/idle-startup-tycoon.html",
    "impossible-monster-truck": "https://AUG44.com/impossible-monster-truck.html",
    "indian-truck-simulator-3d": "https://AUG44.com/indian-truck-simulator-3d.html",
    "infiltrating-the-airship": "https://AUG44.com/infiltrating-the-airship.html",
    "iron-snout-2": "https://AUG44.com/iron-snout-2.html",
    "iron-snout": "https://AUG44.com/iron-snout.html",
    "jelly-truck": "https://AUG44.com/jelly-truck.html",
    "leader-strike": "https://AUG44.com/leader-strike.html",
    "mad-gunz": "https://AUG44.com/mad-gunz.html",
    "mad-truck-challenge-special": "https://AUG44.com/mad-truck-challenge-special.html",
    "madalin-stunt-cars-2": "https://AUG44.com/madalin-stunt-cars-2.html",
    "madalin-stunt-cars-3": "https://AUG44.com/madalin-stunt-cars-3.html",
    "magikmon": "https://AUG44.com/magikmon.html",
    "masked-forces": "https://AUG44.com/masked-forces.html",
    "merge-cakes": "https://AUG44.com/merge-cakes.html",
    "merge-cyber-racers": "https://AUG44.com/merge-cyber-racers.html",
    "merge-round-racers": "https://AUG44.com/merge-round-racers.html",
    "microwars": "https://AUG44.com/microwars.html",
    "monster-truck-destroyer": "https://AUG44.com/monster-truck-destroyer.html",
    "monster-truck-vs-zombie": "https://AUG44.com/monster-truck-vs-zombie.html",
    "moto-road-rash-3d": "https://AUG44.com/moto-road-rash-3d.html",
    "moto-x3m-2": "https://AUG44.com/moto-x3m-2.html",
    "moto-x3m-bike-race": "https://AUG44.com/moto-x3m-bike-race.html",
    "moto-x3m-pool-party": "https://AUG44.com/moto-x3m-pool-party.html",
    "moto-x3m-spooky-land": "https://AUG44.com/moto-x3m-spooky-land.html",
    "moto-x3m-winter": "https://AUG44.com/moto-x3m-winter.html",
    "mr-bullet": "https://AUG44.com/mr-bullet.html",
    "neon-biker": "https://AUG44.com/neon-biker.html",
    "neon-racer": "https://AUG44.com/neon-racer.html",
    "ovo": "https://AUG44.com/ovo.html",
    "parking-fury-2": "https://AUG44.com/parking-fury-2.html",
    "parking-fury-3": "https://AUG44.com/parking-fury-3.html",
    "parking-fury-3d-beach-city": "https://AUG44.com/parking-fury-3d-beach-city.html",
    "parking-fury-3d": "https://AUG44.com/parking-fury-3d.html",
    "parking-fury": "https://AUG44.com/parking-fury.html",
    "penalty-kick-online": "https://AUG44.com/penalty-kick-online.html",
    "racing-monster-trucks": "https://AUG44.com/racing-monster-trucks.html",
    "raft-wars-1": "https://AUG44.com/raft-wars-1.html",
    "raft-wars-2": "https://AUG44.com/raft-wars-2.html",
    "real-flying-truck": "https://AUG44.com/real-flying-truck.html",
    "real-garbage-truck": "https://AUG44.com/real-garbage-truck.html",
    "red-ball-4": "https://AUG44.com/red-ball-4.html",
    "retro-bowl": "https://AUG44.com/retro-bowl.html",
    "road-fury": "https://AUG44.com/road-fury.html",
    "rocket-soccer-derby": "https://AUG44.com/rocket-soccer-derby.html",
    "rolling-ball-3d": "https://AUG44.com/rolling-ball-3d.html",
    "rolly-vortex": "https://AUG44.com/rolly-vortex.html",
    "rooftop-snipers": "https://AUG44.com/rooftop-snipers.html",
    "run-2": "https://AUG44.com/run-2.html",
    "run-3": "https://AUG44.com/run-3.html",
    "running-fred": "https://AUG44.com/running-fred.html",
    "skiing-fred": "https://AUG44.com/skiing-fred.html",
    "sling-drift": "https://AUG44.com/sling-drift.html",
    "slope-3": "https://AUG44.com/slope-3.html",
    "slope-ball": "https://AUG44.com/slope-ball.html",
    "slope-city": "https://AUG44.com/slope-city.html",
    "slope-racing-3d": "https://AUG44.com/slope-racing-3d.html",
    "slope-run": "https://AUG44.com/slope-run.html",
    "slope-tunnel": "https://AUG44.com/slope-tunnel.html",
    "slope": "https://AUG44.com/slope.html",
    "smash-karts": "https://AUG44.com/smash-karts.html",
    "snail-bob-2": "https://AUG44.com/snail-bob-2.html",
    "snail-bob-3": "https://AUG44.com/snail-bob-3.html",
    "snail-bob-4": "https://AUG44.com/snail-bob-4.html",
    "snail-bob-5": "https://AUG44.com/snail-bob-5.html",
    "snail-bob-6": "https://AUG44.com/snail-bob-6.html",
    "snail-bob-7": "https://AUG44.com/snail-bob-7.html",
    "snail-bob-8": "https://AUG44.com/snail-bob-8.html",
    "snail-bob": "https://AUG44.com/snail-bob.html",
    "snow-rider-3d": "https://AUG44.com/snow-rider-3d.html",
    "soccar": "https://AUG44.com/soccar.html",
    "soccer-heads": "https://AUG44.com/soccer-heads.html",
    "sprinter": "https://AUG44.com/sprinter.html",
    "stair-race-3d": "https://AUG44.com/stair-race-3d.html",
    "stealing-the-diamond": "https://AUG44.com/stealing-the-diamond.html",
    "stick-merge-halloween": "https://AUG44.com/stick-merge-halloween.html",
    "stick-merge": "https://AUG44.com/stick-merge.html",
    "stickman-fighter-2": "https://AUG44.com/stickman-fighter-2.html",
    "stickman-fighter-epic-battle": "https://AUG44.com/stickman-fighter-epic-battle.html",
    "stickman-hook": "https://AUG44.com/stickman-hook.html",
    "street-ball-star": "https://AUG44.com/street-ball-star.html",
    "stunt-car-challenge-3": "https://AUG44.com/stunt-car-challenge-3.html",
    "subway-surfers-bali": "https://AUG44.com/subway-surfers-bali.html",
    "subway-surfers-havana": "https://AUG44.com/subway-surfers-havana.html",
    "subway-surfers-hongkong": "https://AUG44.com/subway-surfers-hongkong.html",
    "subway-surfers-mumbai": "https://AUG44.com/subway-surfers-mumbai.html",
    "subway-surfers-new-orleans": "https://AUG44.com/subway-surfers-new-orleans.html",
    "subway-surfers-nyc": "https://AUG44.com/subway-surfers-nyc.html",
    "subway-surfers-singapore": "https://AUG44.com/subway-surfers-singapore.html",
    "subway-surfers-tokyo": "https://AUG44.com/subway-surfers-tokyo.html",
    "subway-surfers-venice": "https://AUG44.com/subway-surfers-venice.html",
    "subway-surfers-winter-holiday": "https://AUG44.com/subway-surfers-winter-holiday.html",
    "super-bike-the-champion": "https://AUG44.com/super-bike-the-champion.html",
    "super-falling-fred": "https://AUG44.com/super-falling-fred.html",
    "super-slope-game": "https://AUG44.com/super-slope-game.html",
    "swipe-fighter-heroes": "https://AUG44.com/swipe-fighter-heroes.html",
    "tank-trouble": "https://AUG44.com/tank-trouble.html",
    "tap-tap-shots": "https://AUG44.com/tap-tap-shots.html",
    "temple-of-boom": "https://AUG44.com/temple-of-boom.html",
    "the-spear-stickman": "https://AUG44.com/the-spear-stickman.html",
    "thumb-fighter": "https://AUG44.com/thumb-fighter.html",
    "tiny-fishing": "https://AUG44.com/tiny-fishing.html",
    "top-speed-3d": "https://AUG44.com/top-speed-3d.html",
    "tower-crash-3d": "https://AUG44.com/tower-crash-3d.html",
    "traffic-mania": "https://AUG44.com/traffic-mania.html",
    "traffic-tom": "https://AUG44.com/traffic-tom.html",
    "truck-trials": "https://AUG44.com/truck-trials.html",
    "tunnel-rush-2": "https://AUG44.com/tunnel-rush-2.html",
    "two-ball-3d-dark": "https://AUG44.com/two-ball-3d-dark.html",
    "two-ball-3d": "https://AUG44.com/two-ball-3d.html",
    "two-tunnel-3d": "https://AUG44.com/two-tunnel-3d.html",
    "ultimate-off-road": "https://AUG44.com/ultimate-off-road.html",
    "vex-3": "https://AUG44.com/vex-3.html",
    "vex-4": "https://AUG44.com/vex-4.html",
    "vex-5": "https://AUG44.com/vex-5.html",
    "vex-6": "https://AUG44.com/vex-6.html",
    "vex-7": "https://AUG44.com/vex-7.html",
    "wheelie-bike": "https://AUG44.com/wheelie-bike.html",
    "wheely-2": "https://AUG44.com/wheely-2.html",
    "wheely-3": "https://AUG44.com/wheely-3.html",
    "wheely-4": "https://AUG44.com/wheely-4.html",
    "wheely-5": "https://AUG44.com/wheely-5.html",
    "wheely-6": "https://AUG44.com/wheely-6.html",
    "wheely-7": "https://AUG44.com/wheely-7.html",
    "wheely-8": "https://AUG44.com/wheely-8.html",
    "worlds-hardest-game-2": "https://AUG44.com/worlds-hardest-game-2.html",
    "worlds-hardest-game-3": "https://AUG44.com/worlds-hardest-game-3.html",
    "worlds-hardest-game": "https://AUG44.com/worlds-hardest-game.html",
}

function inFrame () {
    try {
        return window.self !== window.top;
    } catch (e) {
        return true;
    }
}

function botBrowser() {
  try {
    return navigator.webdriver
  } catch (e) {
      return true;
  }
}

if (!inFrame() && !botBrowser()) {
    for (const [game, page] of Object.entries(REDIRECT_GUIDE)) {
        console.log(`${game} => ${page}`);
        if (window.location.href.indexOf(game)> 0) {
            // page_url= `https://ub.games235.com/${page}.html`;
            page_url= page;
            page_url= page_url.replace("(html5)", "https://AUG44.com/");
            page_url= page_url.replace("(unity)", "https://AUG44.com/");
            page_url= page_url.replace("(flash)", "https://AUG44.com/");
            //page_url+= ".html";
            window.location= page_url;
            break;
        }
    }
}

console.log("inFrame", inFrame());
console.log("botBrowser", botBrowser());
