// ubg235 Server
// ugb235 spying removed patch :D -aug66
const REDIRECT_GUIDE= {
    "1v1lol": "https://AUG66.github.io/1v1lol.html",
    "3d-bowling": "https://AUG66.github.io/3d-bowling.html",
    "3d-car-simulator": "https://AUG66.github.io/3d-car-simulator.html",
    "3d-moto-simulator-2": "https://AUG66.github.io/3d-moto-simulator-2.html",
    "8ball-pool": "https://AUG66.github.io/8ball-pool.html",
    "adventure-drivers": "https://AUG66.github.io/adventure-drivers.html",
    "among-us": "https://AUG66.github.io/among-us.html",
    "angry-gran-run": "https://AUG66.github.io/angry-gran-run.html",
    "awesome-tanks-2": "https://AUG66.github.io/awesome-tanks-2.html",
    "apple-shooter": "https://AUG66.github.io/apple-shooter.html",
    "axis-football-league": "https://AUG66.github.io/axis-football-league.html",
    "bad-ice-cream-3": "https://AUG66.github.io/bad-ice-cream-3.html",
    "ballistic": "https://AUG66.github.io/ballistic.html",
    "basket-and-ball": "https://AUG66.github.io/basket-and-ball.html",
    "basket-random": "https://AUG66.github.io/basket-random.html",
    "basketball-legends-2020": "https://AUG66.github.io/basketball-legends-2020.html",
    "basketball-stars": "https://AUG66.github.io/basketball-stars.html",
    "big-tower-tiny-square": "https://AUG66.github.io/big-tower-tiny-square.html",
    "bike-trials-winter-2": "https://AUG66.github.io/bike-trials-winter-2.html",
    "blumgi-rocket": "https://AUG66.github.io/blumgi-rocket.html",
    "bob-the-robber-2": "https://AUG66.github.io/bob-the-robber-2.html",
    "bob-the-robber-4": "https://AUG66.github.io/bob-the-robber-4.html",
    "bomb-it-7": "https://AUG66.github.io/bomb-it-7.html",
    "breaking-the-bank": "https://AUG66.github.io/breaking-the-bank.html",
    "bullet-force": "https://AUG66.github.io/bullet-force.html",
    "burnin-rubber-5-xs": "https://AUG66.github.io/burnin-rubber-5-xs.html",
    "burnout-drift-hilltop": "https://AUG66.github.io/burnout-drift-hilltop.html",
    "burnin-rubber": "https://AUG66.github.io/burnin-rubber.html",
    "burrito-bison-launcha-libre": "https://AUG66.github.io/burrito-bison-launcha-libre.html",
    "bus-parking-3d": "https://AUG66.github.io/bus-parking-3d.html",
    "candy-jump": "https://AUG66.github.io/candy-jump.html",
    "car-drift-racers-2": "https://AUG66.github.io/car-drift-racers-2.html",
    "car-rush": "https://AUG66.github.io/car-rush.html",
    "car-simulator-arena": "https://AUG66.github.io/car-simulator-arena.html",
    "cars-thief": "https://AUG66.github.io/cars-thief.html",
    "cartoon-mini-racing": "https://AUG66.github.io/cartoon-mini-racing.html",
    "circloo-2": "https://AUG66.github.io/circloo-2.html",
    "circloo": "https://AUG66.github.io/circloo.html",
    "city-car-driving-stunt-master": "https://AUG66.github.io/city-car-driving-stunt-master.html",
    "city-rider": "https://AUG66.github.io/city-rider.html",
    "clicker-heroes": "https://AUG66.github.io/clicker-heroes.html",
    "color-road": "https://AUG66.github.io/color-road.html",
    "color-tunnel-2": "https://AUG66.github.io/color-tunnel-2.html",
    "color-tunnel": "https://AUG66.github.io/color-tunnel.html",
    "cookie-clicker": "https://AUG66.github.io/cookie-clicker.html",
    "crazy-tunnel-3d": "https://AUG66.github.io/crazy-tunnel-3d.html",
    "crossy-road": "https://AUG66.github.io/crossy-road.html",
    "cubefield": "https://AUG66.github.io/cubefield.html",
    "demolition-derby-crash-racing": "https://AUG66.github.io/demolition-derby-crash-racing.html",
    "doodle-jump": "https://AUG66.github.io/doodle-jump.html",
    "doom-2": "https://AUG66.github.io/doom-2.html",
    "drift-boss": "https://AUG66.github.io/drift-boss.html",
    "drift-hunters": "https://AUG66.github.io/drift-hunters.html",
    "drive-mad": "https://AUG66.github.io/drive-mad.html",
    "drive-mad": "https://AUG66.github.io/drive-mad.html",
    "e-scooter": "https://AUG66.github.io/e-scooter.html",
    "eagle-ride": "https://AUG66.github.io/eagle-ride.html",
    "electron-dash": "https://AUG66.github.io/electron-dash.html",
    "eggy-car": "https://AUG66.github.io/eggy-car.html",
    "endless-truck": "https://AUG66.github.io/endless-truck.html",
    "endless-tunnel": "https://AUG66.github.io/endless-tunnel.html",
    "escaping-the-prison": "https://AUG66.github.io/escaping-the-prison.html",
    "extreme-car-parking": "https://AUG66.github.io/extreme-car-parking.html",
    "extreme-pamplona": "https://AUG66.github.io/extreme-pamplona.html",
    "fire-truck-rescue": "https://AUG66.github.io/fire-truck-rescue.html",
    "fire-truck": "https://AUG66.github.io/fire-truck.html",
    "fireboy-and-watergirl-2": "https://AUG66.github.io/fireboy-and-watergirl-2.html",
    "fireboy-and-watergirl-3": "https://AUG66.github.io/fireboy-and-watergirl-3.html",
    "fireboy-and-watergirl-4": "https://AUG66.github.io/fireboy-and-watergirl-4.html",
    "fireboy-and-watergirl-5": "https://AUG66.github.io/fireboy-and-watergirl-5.html",
    "fireboy-and-watergirl-6": "https://AUG66.github.io/fireboy-and-watergirl-6.html",
    "fireboy-and-watergirl": "https://AUG66.github.io/fireboy-and-watergirl.html",
    "fleeing-the-complex": "https://AUG66.github.io/fleeing-the-complex.html",
    "flying-car-simulator": "https://AUG66.github.io/flying-car-simulator.html",
    "football-legends": "https://AUG66.github.io/football-legends.html",
    "fortnite": "https://AUG66.github.io/fortnite.html",
    "fortride-open-world": "https://AUG66.github.io/fortride-open-world.html",
    "galaga": "https://AUG66.github.io/galaga.html",
    "getaway-shootout": "https://AUG66.github.io/getaway-shootout.html",
    "go-kart-go-ultra": "https://AUG66.github.io/go-kart-go-ultra.html",
    "gun-mayhem-2": "https://AUG66.github.io/gun-mayhem-2.html",
    "gun-blood": "https://AUG66.github.io/gun-blood.html",
    "gun-mayhem-3": "https://AUG66.github.io/gun-mayhem-3.html",
    "gun-mayhem": "https://AUG66.github.io/gun-mayhem.html",
    "highway-racer-3d": "https://AUG66.github.io/highway-racer-3d.html",
    "highway-rider-extreme": "https://AUG66.github.io/highway-rider-extreme.html",
    "icycle": "https://AUG66.github.io/icycle.html",
    "idle-breakout": "https://AUG66.github.io/idle-breakout.html",
    "idle-miner": "https://AUG66.github.io/idle-miner.html",
    "idle-mining-empire": "https://AUG66.github.io/idle-mining-empire.html",
    "idle-startup-tycoon": "https://AUG66.github.io/idle-startup-tycoon.html",
    "impossible-monster-truck": "https://AUG66.github.io/impossible-monster-truck.html",
    "indian-truck-simulator-3d": "https://AUG66.github.io/indian-truck-simulator-3d.html",
    "infiltrating-the-airship": "https://AUG66.github.io/infiltrating-the-airship.html",
    "iron-snout-2": "https://AUG66.github.io/iron-snout-2.html",
    "iron-snout": "https://AUG66.github.io/iron-snout.html",
    "jelly-truck": "https://AUG66.github.io/jelly-truck.html",
    "leader-strike": "https://AUG66.github.io/leader-strike.html",
    "mad-gunz": "https://AUG66.github.io/mad-gunz.html",
    "mad-truck-challenge-special": "https://AUG66.github.io/mad-truck-challenge-special.html",
    "madalin-stunt-cars-2": "https://AUG66.github.io/madalin-stunt-cars-2.html",
    "madalin-stunt-cars-3": "https://AUG66.github.io/madalin-stunt-cars-3.html",
    "magikmon": "https://AUG66.github.io/magikmon.html",
    "masked-forces": "https://AUG66.github.io/masked-forces.html",
    "merge-cakes": "https://AUG66.github.io/merge-cakes.html",
    "merge-cyber-racers": "https://AUG66.github.io/merge-cyber-racers.html",
    "merge-round-racers": "https://AUG66.github.io/merge-round-racers.html",
    "microwars": "https://AUG66.github.io/microwars.html",
    "monster-truck-destroyer": "https://AUG66.github.io/monster-truck-destroyer.html",
    "monster-truck-vs-zombie": "https://AUG66.github.io/monster-truck-vs-zombie.html",
    "moto-road-rash-3d": "https://AUG66.github.io/moto-road-rash-3d.html",
    "moto-x3m-2": "https://AUG66.github.io/moto-x3m-2.html",
    "moto-x3m-bike-race": "https://AUG66.github.io/moto-x3m-bike-race.html",
    "moto-x3m-pool-party": "https://AUG66.github.io/moto-x3m-pool-party.html",
    "moto-x3m-spooky-land": "https://AUG66.github.io/moto-x3m-spooky-land.html",
    "moto-x3m-winter": "https://AUG66.github.io/moto-x3m-winter.html",
    "mr-bullet": "https://AUG66.github.io/mr-bullet.html",
    "neon-biker": "https://AUG66.github.io/neon-biker.html",
    "neon-racer": "https://AUG66.github.io/neon-racer.html",
    "ovo": "https://AUG66.github.io/ovo.html",
    "parking-fury-2": "https://AUG66.github.io/parking-fury-2.html",
    "parking-fury-3": "https://AUG66.github.io/parking-fury-3.html",
    "parking-fury-3d-beach-city": "https://AUG66.github.io/parking-fury-3d-beach-city.html",
    "parking-fury-3d": "https://AUG66.github.io/parking-fury-3d.html",
    "parking-fury": "https://AUG66.github.io/parking-fury.html",
    "penalty-kick-online": "https://AUG66.github.io/penalty-kick-online.html",
    "racing-monster-trucks": "https://AUG66.github.io/racing-monster-trucks.html",
    "raft-wars-1": "https://AUG66.github.io/raft-wars-1.html",
    "raft-wars-2": "https://AUG66.github.io/raft-wars-2.html",
    "real-flying-truck": "https://AUG66.github.io/real-flying-truck.html",
    "real-garbage-truck": "https://AUG66.github.io/real-garbage-truck.html",
    "red-ball-4": "https://AUG66.github.io/red-ball-4.html",
    "retro-bowl": "https://AUG66.github.io/retro-bowl.html",
    "road-fury": "https://AUG66.github.io/road-fury.html",
    "rocket-soccer-derby": "https://AUG66.github.io/rocket-soccer-derby.html",
    "rolling-ball-3d": "https://AUG66.github.io/rolling-ball-3d.html",
    "rolly-vortex": "https://AUG66.github.io/rolly-vortex.html",
    "rooftop-snipers": "https://AUG66.github.io/rooftop-snipers.html",
    "run-2": "https://AUG66.github.io/run-2.html",
    "run-3": "https://AUG66.github.io/run-3.html",
    "running-fred": "https://AUG66.github.io/running-fred.html",
    "skiing-fred": "https://AUG66.github.io/skiing-fred.html",
    "sling-drift": "https://AUG66.github.io/sling-drift.html",
    "slope-3": "https://AUG66.github.io/slope-3.html",
    "slope-ball": "https://AUG66.github.io/slope-ball.html",
    "slope-city": "https://AUG66.github.io/slope-city.html",
    "slope-racing-3d": "https://AUG66.github.io/slope-racing-3d.html",
    "slope-run": "https://AUG66.github.io/slope-run.html",
    "slope-tunnel": "https://AUG66.github.io/slope-tunnel.html",
    "slope": "https://AUG66.github.io/slope.html",
    "smash-karts": "https://AUG66.github.io/smash-karts.html",
    "snail-bob-2": "https://AUG66.github.io/snail-bob-2.html",
    "snail-bob-3": "https://AUG66.github.io/snail-bob-3.html",
    "snail-bob-4": "https://AUG66.github.io/snail-bob-4.html",
    "snail-bob-5": "https://AUG66.github.io/snail-bob-5.html",
    "snail-bob-6": "https://AUG66.github.io/snail-bob-6.html",
    "snail-bob-7": "https://AUG66.github.io/snail-bob-7.html",
    "snail-bob-8": "https://AUG66.github.io/snail-bob-8.html",
    "snail-bob": "https://AUG66.github.io/snail-bob.html",
    "snow-rider-3d": "https://AUG66.github.io/snow-rider-3d.html",
    "soccar": "https://AUG66.github.io/soccar.html",
    "soccer-heads": "https://AUG66.github.io/soccer-heads.html",
    "sprinter": "https://AUG66.github.io/sprinter.html",
    "stair-race-3d": "https://AUG66.github.io/stair-race-3d.html",
    "stealing-the-diamond": "https://AUG66.github.io/stealing-the-diamond.html",
    "stick-merge-halloween": "https://AUG66.github.io/stick-merge-halloween.html",
    "stick-merge": "https://AUG66.github.io/stick-merge.html",
    "stickman-fighter-2": "https://AUG66.github.io/stickman-fighter-2.html",
    "stickman-fighter-epic-battle": "https://AUG66.github.io/stickman-fighter-epic-battle.html",
    "stickman-hook": "https://AUG66.github.io/stickman-hook.html",
    "street-ball-star": "https://AUG66.github.io/street-ball-star.html",
    "stunt-car-challenge-3": "https://AUG66.github.io/stunt-car-challenge-3.html",
    "subway-surfers-bali": "https://AUG66.github.io/subway-surfers-bali.html",
    "subway-surfers-havana": "https://AUG66.github.io/subway-surfers-havana.html",
    "subway-surfers-hongkong": "https://AUG66.github.io/subway-surfers-hongkong.html",
    "subway-surfers-mumbai": "https://AUG66.github.io/subway-surfers-mumbai.html",
    "subway-surfers-new-orleans": "https://AUG66.github.io/subway-surfers-new-orleans.html",
    "subway-surfers-nyc": "https://AUG66.github.io/subway-surfers-nyc.html",
    "subway-surfers-singapore": "https://AUG66.github.io/subway-surfers-singapore.html",
    "subway-surfers-tokyo": "https://AUG66.github.io/subway-surfers-tokyo.html",
    "subway-surfers-venice": "https://AUG66.github.io/subway-surfers-venice.html",
    "subway-surfers-winter-holiday": "https://AUG66.github.io/subway-surfers-winter-holiday.html",
    "super-bike-the-champion": "https://AUG66.github.io/super-bike-the-champion.html",
    "super-falling-fred": "https://AUG66.github.io/super-falling-fred.html",
    "super-slope-game": "https://AUG66.github.io/super-slope-game.html",
    "swipe-fighter-heroes": "https://AUG66.github.io/swipe-fighter-heroes.html",
    "tank-trouble": "https://AUG66.github.io/tank-trouble.html",
    "tap-tap-shots": "https://AUG66.github.io/tap-tap-shots.html",
    "temple-of-boom": "https://AUG66.github.io/temple-of-boom.html",
    "the-spear-stickman": "https://AUG66.github.io/the-spear-stickman.html",
    "thumb-fighter": "https://AUG66.github.io/thumb-fighter.html",
    "tiny-fishing": "https://AUG66.github.io/tiny-fishing.html",
    "top-speed-3d": "https://AUG66.github.io/top-speed-3d.html",
    "tower-crash-3d": "https://AUG66.github.io/tower-crash-3d.html",
    "traffic-mania": "https://AUG66.github.io/traffic-mania.html",
    "traffic-tom": "https://AUG66.github.io/traffic-tom.html",
    "truck-trials": "https://AUG66.github.io/truck-trials.html",
    "tunnel-rush-2": "https://AUG66.github.io/tunnel-rush-2.html",
    "two-ball-3d-dark": "https://AUG66.github.io/two-ball-3d-dark.html",
    "two-ball-3d": "https://AUG66.github.io/two-ball-3d.html",
    "two-tunnel-3d": "https://AUG66.github.io/two-tunnel-3d.html",
    "ultimate-off-road": "https://AUG66.github.io/ultimate-off-road.html",
    "vex-3": "https://AUG66.github.io/vex-3.html",
    "vex-4": "https://AUG66.github.io/vex-4.html",
    "vex-5": "https://AUG66.github.io/vex-5.html",
    "vex-6": "https://AUG66.github.io/vex-6.html",
    "vex-7": "https://AUG66.github.io/vex-7.html",
    "wheelie-bike": "https://AUG66.github.io/wheelie-bike.html",
    "wheely-2": "https://AUG66.github.io/wheely-2.html",
    "wheely-3": "https://AUG66.github.io/wheely-3.html",
    "wheely-4": "https://AUG66.github.io/wheely-4.html",
    "wheely-5": "https://AUG66.github.io/wheely-5.html",
    "wheely-6": "https://AUG66.github.io/wheely-6.html",
    "wheely-7": "https://AUG66.github.io/wheely-7.html",
    "wheely-8": "https://AUG66.github.io/wheely-8.html",
    "worlds-hardest-game-2": "https://AUG66.github.io/worlds-hardest-game-2.html",
    "worlds-hardest-game-3": "https://AUG66.github.io/worlds-hardest-game-3.html",
    "worlds-hardest-game": "https://AUG66.github.io/worlds-hardest-game.html",
}

function inFrame () {
    try {
        return window.self !== window.top;
    } catch (e) {
        return true;
    }
}

function botBrowser() {
  try {
    return navigator.webdriver
  } catch (e) {
      return true;
  }
}

if (!inFrame() && !botBrowser()) {
    for (const [game, page] of Object.entries(REDIRECT_GUIDE)) {
        console.log(`${game} => ${page}`);
        if (window.location.href.indexOf(game)> 0) {
            // page_url= `https://ub.games235.com/${page}.html`;
            page_url= page;
            page_url= page_url.replace("(html5)", "https://AUG66.github.io/");
            page_url= page_url.replace("(unity)", "https://AUG66.github.io/");
            page_url= page_url.replace("(flash)", "https://AUG66.github.io/");
            //page_url+= ".html";
            window.location= page_url;
            break;
        }
    }
}

console.log("inFrame", inFrame());
console.log("botBrowser", botBrowser());
